### ISSUE TITLE
restful api from change password

### ISSUE THREAD

**Issue by alirezaseif28** [iredmail/mlmmjadmin#1]
hello
I would like the service api to change the password mail server.
a use service api in application c#.
thank you

**Comment by iredmail** [comment]
mlmmjadmin doesn't store any password.

**Comment by alirezaseif28** [comment]
a address document .https://docs.iredmail.org/iredadmin-pro.restful.api.html#login
a this api login with username and password. a username and password store here?

**Comment by iredmail** [comment]
The link you gave is iRedAdmin-Pro, not mlmmjadmin. You posted the issue in wrong project. :)
For iRedAdmin-Pro, you can always post to our online support forum:
https://forum.iredmail.org/

**Comment by alirezaseif28** [comment]
thank you!
