### ISSUE TITLE
mlmmjadmin does not verify credential token properly

### ISSUE THREAD

**Issue by TerjeBr** [iredmail/mlmmjadmin#14]
*To reproduce*
Once mlmmjadmin server starts, do either of the following:

* fire a http API request with valid token. The server validates the token and perform the requests. For all follow-on requests, no matter it comes with token or not, they all succeed.

* fire a http API request without token or invalid token. The server validates the token and throw NO_API_AUTH_TOKEN error. For all follow-on requests, even if it comes with valid token, the same error is thrown.

*Details*
See the source code for the subscriber.py:

https://github.com/iredmail/mlmmjadmin/blob/4e074892e9b7010efa26ef7f5a226531fd01b65b/controllers/subscriber.py#L13

The implementations of each view are decorated by api_acl which takes care of authentication check. This decorator only gets invoked the first time on the very first request received when the server is up. After that the function that was returned by the decorator the first time is used over and over again.

*Expected behaviour*
mlmmjadmin server should verify token on each and every request

**Comment by iredmail** [comment]
hi @TerjeBr 

Do you have some (shell/python/...) commands to reproduce the issue? It will be helpful for us to reproduce it quickly and fix it.

**Comment by TerjeBr** [comment]
Any valid request to the mljmmadmin rest API will do. You have to set up mljmmadmin, and then you can use f.ex. curl or postman to send a request.

**Comment by TerjeBr** [comment]
The token I am talking about is the "X-MLMMJADMIN-API-AUTH-TOKEN" header in the HTTP request.

**Comment by TerjeBr** [comment]
This is a huge security issue. Once your mlmmjadmin server is up and running, and the first request has been successful, then it means that anyone with internet access to the server can issue requests and change any or all of the mailinglists as they see fit. It does not matter which "X-MLMMJADMIN-API-AUTH-TOKEN" they use, or if they use a token at all. All requests just goes through.

On the other hand, if you restart the mlmmjadmin server and the first request has no token (or an invalid token), then your server will never work (at least not until you restart it again). It will just decline all requests, also those with a valid token.

**Comment by iredmail** [comment]
- I can reproduce the issue, working on it.
- It's an issue, but i don't consider it as "huge security" issue.

**Comment by TerjeBr** [comment]
Hi. You have not commented on my PR yet. What are your thoughts?
When will you get around to looking at this?

**Comment by iredmail** [comment]
Hi @TerjeBr 

Thanks for your PR and sorry about my late reply.
Was busy these 2 days, i will review and test it later, hopefully before weekend.

**Comment by TerjeBr** [comment]
Any new estimate on when you will get around to look at this?
