### ISSUE TITLE
upgrade_mlmmjadmin.sh fails on Debian 11: Unsupported Linux/BSD distribution or release, abort.

### ISSUE THREAD

**Issue by richardebeling** [iredmail/mlmmjadmin#19]
upgrade_mlmmjadmin.sh currently [only checks for debian 9 and 10, but not for 11](https://github.com/iredmail/mlmmjadmin/blob/master/tools/upgrade_mlmmjadmin.sh#L75):
```bash
        # Set distro code name and unsupported releases.
        if grep -i '^10' /etc/debian_version &>/dev/null; then
            export DISTRO_VERSION='10'
            export UWSGI_PY3_PLUGIN_NAME='python37'
        elif grep '^9' /etc/debian_version &>/dev/null || \
            grep -i '^stretch' /etc/debian_version &>/dev/null; then
            export DISTRO_VERSION='9'
            export UWSGI_PY3_PLUGIN_NAME='python35'
        else
            export UNSUPPORTED_RELEASE="YES"
        fi
```

On debian 11, this leads to the script exiting with:
```
Unsupported Linux/BSD distribution or release, abort.
```

This conflicts iRedMail's [README.md](https://github.com/iredmail/iRedMail/blob/master/README.md), which says that Debian 11 is suported and recommended

**Comment by iredmail** [comment]
Dear @He3lixxx 

Thank you very much for the feedback. mlmmjadmin-3.1.3 has been tagged with this fix, please download 3.1.3 and upgrade. :)
https://github.com/iredmail/mlmmjadmin/tags
