### ISSUE TITLE
upgrade_mlmmjadmin.sh fails on FreeBSD 13

### ISSUE THREAD

**Issue by elchy** [iredmail/mlmmjadmin#20]
`KERNEL_NAME="$(uname -s | tr '[a-z]' '[A-Z]')"` obviously doesn't work on FreeBSD (13.0-RELEASE-p4, current port tree). I replaced that with `export KERNEL_NAME="$(uname -s | tr '[:lower:]' '[:upper:]')"` to fix this.

On FreeBSD, the script checks for `CMD_PIP3='/usr/local/bin/pip3'` but the port `devel/py-pip` doesn't install that file but only `/usr/local/bin/pip` which is a symlink to `/usr/local/bin/pip-3.8`.

**Comment by iredmail** [comment]
Dear @elchy,

- What's the full output of command `uname -s` on your FreeBSD 13.0-RELEASE-p4?
- What error and output did you get with command `uname -s | tr '[a-z]' '[A-Z]'`?

**Comment by elchy** [comment]
Probably my fault to not use the default LANG variable...
`% echo $LANG`
`en_US.ISO8859-1`
`% uname -s`
`FreeBSD`
`% uname -s | tr '[a-z]' '[A-Z]'`
`Gs??Ct?`
`% uname -s | tr '[:lower:]' '[:upper:]'`
`FREEBSD`
... setting $LANG to the default makes the translation work correctly.
`% export LANG=C.UTF8`
`% uname -s | tr '[a-z]' '[A-Z]'`
`FREEBSD`

**Comment by iredmail** [comment]
Fixed this bug moment ago. Thank you very much for the feedback. :)

**Comment by iredmail** [comment]
Oops, i just realize that we have this fix in iRedAdmin upgrade script, but you reported same issue with iRedAdmin.
Could you please try the fix and let me know how it works on your system?
https://github.com/iredmail/mlmmjadmin/commit/6d138af7fcfe8fe437a5bbd27710b830684bf4da

**Comment by elchy** [comment]
You're right, `upgrade_iredadmin.sh` workes out-of-the-box. `export LC_ALL='C'` does the trick.

Thanks for fixing it in the other upgrade scripts.

**Comment by iredmail** [comment]
Thanks for the feedback. :)
