### ISSUE TITLE
upgrade_mlmmjadmin.sh fails on Debian 12: Unsupported Linux/BSD distribution or release, abort.

### ISSUE THREAD

**Issue by BoBeR182** [iredmail/mlmmjadmin#21]
https://github.com/iredmail/mlmmjadmin/blob/master/tools/upgrade_mlmmjadmin.sh#L79C1-L96C17

Please update to support Debian 12

**Comment by iredmail** [comment]
Fixed in v3.1.8:
https://github.com/iredmail/mlmmjadmin/releases/tag/3.1.8

Thanks for the feedback. :)
