### ISSUE TITLE
API Call - add_subscribers

### ISSUE THREAD

**Issue by sgroom-lb** [iredmail/mlmmjadmin#25]
Properly formatted / tokened API Call - add_subscribers fails if require_confirm is set to no. Same call with require_confirm set to yes succeeds. Pls advise

**Comment by iredmail** [comment]
Could you share the api calls (e.g. curl command with arguments) to help me reproduce this issue?
Also tell me the result you expect.

**Comment by sgroom-lb** [comment]
all original data is valid, redacted as necessary

curl -X POST "http://127.0.0.1:7790/api/listname@domain.com" -H "X_MLMMJADMIN_API_AUTH_TOKEN: redacted" -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "add_subscribers=new.subscriber@somedomain" --data-urlencode "require_confirm=no"  --data-urlencode "subscription=normal"

I expect the email to be subscribed to the list without a confirmation email as member emails are already vetted by org prior to membership. Even if you get a success return code, user isn't subscribed to the list.

*bump*

**Comment by iredmail** [comment]
Hi @sgroom-lb 

- To add subscribers, you should make API calls to endpoint `/api/<list-email>/subscribers`, not `/api/<list-email>` (it doesn't support `add_subscribers` parameter at all). Please check the API document here: https://github.com/iredmail/mlmmjadmin/blob/master/docs/API.md
- You mentioned `fails`, but what kind of failure are we talking about? Did you get any error message report by mlmmjadmin?

It's recommended to manage mlmmj mailing list with /opt/mlmmjadmin/tools/maillist_admin.py. FYI https://docs.iredmail.org/manage.subscribeable.mailing.lists.html
